version: '3.7'

services:
  site:
    image: wordpress
    depends_on:
      - db
    ports:
      - "80:80"
    volumes:
      - ./site-storage:/var/www/html
      - ./preparation-moteur:/var/www/html/wp-content/plugins/preparation-moteur
    environment:
      WORDPRESS_DB_HOST: "db"
      WORDPRESS_DB_NAME: "b80so_WP379999"
      WORDPRESS_DB_USER: "root"
      WORDPRESS_DB_PASSWORD: "rootpass"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 0s

  db:
    image: mysql:5.6
    volumes:
      - ./db-storage:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "rootpass"
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "dbpass"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 0s

#  adminer:
#    image: adminer:latest
#    depends_on:
#      - db
#    ports:
#      - "8080:8080"
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost"]
#      interval: 1m
#      timeout: 30s
#      retries: 3
#      start_period: 0s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "dbpass"
      MYSQL_ROOT_PASSWORD: "rootpass"
      PMA_HOST: db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 0s


# vim: ft=yaml tw=80 et ts=2 sw=2 sts=2
